# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk12

services:
  - postgresql

# используем режим обычного пользователя для сборки проекта.
sudo: false

before_install:
  - psql -c 'create database tracker;' -U tracker_app

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - ukarpov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="1fb19c1e-937c-468d-bf8f-cb682e31ee5e"